slice_name: Balance per month (debt is negative)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month_start
  time_grain_sqla: P1M
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(signed_closing_balance)
    label: Closing balance
  groupby:
  - bank
  - account_last4
  adhoc_filters:
  - expressionType: SIMPLE
    subject: month_start
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
  area: true
  opacity: 0.25
  markerEnabled: true
  markerSize: 6
  seriesType: smooth
  x_axis_time_format: '%d %b %Y'
  y_axis_format: ',.0f'
  rich_tooltip: true
  row_limit: 10000
  show_legend: true
  datasource: 13__table
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: 36343172-f26c-5149-9619-3a7abdb2a66d
version: 1.0.0
dataset_uuid: c86e2242-660c-530a-a3af-77b867584bc3
