slice_name: 'Investments: return and how each month closed'
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  query_mode: raw
  adhoc_filters:
  - expressionType: SIMPLE
    subject: month_start
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
  all_columns:
  - month_start
  - place
  - currency
  - return_pct
  - closing_basis
  - is_return_reliable
  - gain
  - closing_balance
  order_by_cols:
  - '["month_start", false]'
  row_limit: 1000
  include_search: true
  datasource: 3__table
  viz_type: table
query_context: null
cache_timeout: null
uuid: 1d410045-9b39-42b5-b5bc-227fc22a1a60
version: 1.0.0
dataset_uuid: 8dbb27ad-d9fd-4a29-a15f-976798d38dd4
