slice_name: 'Investments: return per fund over time'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month_start
  time_grain_sqla: P1M
  metrics:
  - expressionType: SQL
    sqlExpression: MAX(return_pct)
    label: Return
  groupby:
  - place
  adhoc_filters:
  - expressionType: SIMPLE
    subject: month_start
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
  - expressionType: SQL
    sqlExpression: is_return_reliable
    clause: WHERE
  markerEnabled: true
  seriesType: smooth
  y_axis_format: .2%
  x_axis_time_format: '%d %b %Y'
  rich_tooltip: true
  row_limit: 10000
  show_legend: true
  datasource: 3__table
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: 0c37ec9b-5f2b-4053-bfaf-3ea7e6c8ee40
version: 1.0.0
dataset_uuid: 48678c06-e719-43d6-ab1f-4ec1e7eace54
