slice_name: 'Investments: return and how each month closed'
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  query_mode: raw
  all_columns:
  - month_start
  - place
  - currency
  - return_pct
  - closing_basis
  - is_return_reliable
  - gain
  - closing_balance
  order_by_cols:
  - '["month_start", false]'
  row_limit: 1000
  include_search: true
  datasource: 3__table
  viz_type: table
query_context: null
cache_timeout: null
uuid: 46e7c38e-909b-473e-b8a2-509d34946f7e
version: 1.0.0
dataset_uuid: e41c065e-aaaa-4ce3-878a-3d8e5cc35092
