slice_name: 'Investments: return per fund over time'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month_start
  time_grain_sqla: P1M
  metrics:
  - expressionType: SQL
    sqlExpression: MAX(return_pct)
    label: Return
  groupby:
  - place
  - currency
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: is_return_reliable
    clause: WHERE
  y_axis_format: .2%
  x_axis_time_format: '%Y-%m-%d'
  row_limit: 10000
  show_legend: true
  datasource: 3__table
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: cde5a388-53c2-43ef-a72e-7aa61eaeb7e3
version: 1.0.0
dataset_uuid: e41c065e-aaaa-4ce3-878a-3d8e5cc35092
