slice_name: 'Investments: return per fund over time'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month_start
  time_grain_sqla: P1M
  metrics:
  - expressionType: SQL
    sqlExpression: MAX(return_pct)
    label: Return
  groupby:
  - place
  - currency
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: is_return_reliable
    clause: WHERE
  y_axis_format: .2%
  x_axis_time_format: '%Y-%m-%d'
  row_limit: 10000
  show_legend: true
  datasource: 3__table
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: fb9f4899-dbb9-497a-8e32-2a4696d37605
version: 1.0.0
dataset_uuid: fec30a31-fd6f-40ff-ae53-6d89f74d97e3
