slice_name: 'Investments: return per fund over time'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month_start
  time_grain_sqla: P1M
  metrics:
  - expressionType: SQL
    sqlExpression: MAX(return_pct)
    label: Return
  groupby:
  - place
  adhoc_filters:
  - expressionType: SIMPLE
    subject: month_start
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
  - expressionType: SQL
    sqlExpression: is_return_reliable
    clause: WHERE
  markerEnabled: true
  seriesType: smooth
  y_axis_format: .2%
  x_axis_time_format: '%d %b %Y'
  rich_tooltip: true
  row_limit: 10000
  show_legend: true
  datasource: 14__table
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: 77bb74fe-4bbd-527b-af20-060bbc44471a
version: 1.0.0
dataset_uuid: 673c06bf-c577-5fb4-b52b-54ddbe349e43
