slice_name: Savings balance per month (asset accounts)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month_start
  time_grain_sqla: P1M
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(closing_balance)
    label: Closing balance
  groupby:
  - bank
  - currency
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: account_kind = 'asset'
    clause: WHERE
  x_axis_time_format: '%Y-%m-%d'
  row_limit: 10000
  show_legend: true
  datasource: 2__table
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: 9eb1d4e8-269f-44f5-8936-558889ac6ccf
version: 1.0.0
dataset_uuid: 639575b8-1e5d-4059-90cf-a7b775e655d6
